name: 'Setup Node.js Environment'
description: 'Setup Node.js, install dependencies, and configure environment for CI jobs'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'
  cache-key:
    description: 'Cache key for npm'
    required: false
    default: 'npm'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache-key }}
        
    - name: Install dependencies
      run: npm run install:all
      shell: bash
