# Railway configuration for Chef Chopsky Agent Service
# This file tells Railway how to build and run the Node.js service

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
