# Railway Config as Code for Chef Chopsky Agent Service
# This file defines the complete deployment configuration for the agent service
# See: https://docs.railway.com/reference/config-as-code

[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node dist/src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Service configuration
[service]
name = "chef-chopsky-agent"
description = "Chef Chopsky AI Agent Service - LangChain-powered cooking assistant"

# Environment-specific settings
[environments.production]
# Production-specific overrides can go here
# Note: Environment variables are managed separately via Railway dashboard or CLI

[environments.staging]
# Staging-specific overrides can go here
# Note: Environment variables are managed separately via Railway dashboard or CLI

# Resource limits and scaling
[resources]
# Memory and CPU limits can be specified here
# Railway will auto-scale based on usage

# Networking configuration
[networking]
# Port configuration
# Railway automatically sets PORT environment variable

# Monitoring and observability
[monitoring]
# Health check configuration
healthcheckPath = "/health"
healthcheckTimeout = 300

# Logging configuration
[logging]
# Log level and format settings
level = "info"
